export const CLOSE_WON_MODAL = 'CLOSE_WON_MODAL';
export const OPEN_WON_MODAL = 'OPEN_WON_MODAL';

export const CLOSE_LOST_MODAL = 'CLOSE_LOST_MODAL';
export const OPEN_LOST_MODAL = 'OPEN_LOST_MODAL';

export const CLOSE_PLAY_MODAL = 'CLOSE_PLAY_MODAL';
export const OPEN_PLAY_MODAL = 'OPEN_PLAY_MODAL';

export const CLOSE_QUIZE_MODAL = 'CLOSE_QUIZE_MODAL';
export const OPEN_QUIZE_MODAL = 'OPEN_QUIZE_MODAL';

export const CLOSE_REQUEST_MODAL = 'CLOSE_REQUEST_MODAL';
export const OPEN_REQUEST_MODAL = 'OPEN_REQUEST_MODAL';


export const CLOSE_LOADING_MODAL = 'CLOSE_LOADING_MODAL';
export const OPEN_LOADING_MODAL = 'OPEN_LOADING_MODAL';

export const CLOSE_AWAITING_RESULTS_MODAL = 'CLOSE_AWAITING_RESULTS_MODAL';
export const OPEN_AWAITING_RESULTS_MODAL = 'OPEN_AWAITING_RESULTS_MODAL';

export const CLOSE_EXPIRED_REQUEST_MODAL = 'CLOSE_EXPIRED_REQUEST_MODAL';
export const OPEN_EXPIRED_REQUEST_MODAL = 'OPEN_EXPIRED_REQUEST_MODAL';
